// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CreateGroup(arg1:Array<number>):Promise<model.Group>;

export function GetGroupById(arg1:number):Promise<model.Group>;

export function GetMessages():Promise<Array<model.Message>>;

export function GetSelf():Promise<model.User>;

export function GetUserById(arg1:number):Promise<model.User>;

export function GetUsers():Promise<Array<model.User>>;

export function Greet(arg1:string):Promise<string>;

export function Login(arg1:number,arg2:string):Promise<model.User>;

export function Logout():Promise<void>;

export function Ping():Promise<string>;

export function ReceiveMessage(arg1:model.Message):Promise<Error>;

export function Register(arg1:string,arg2:string):Promise<model.User>;

export function SendMessage(arg1:model.Message):Promise<Error>;

export function UpdateUser():Promise<model.User>;
