// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUserById(arg1) {
  return window['go']['main']['App']['GetUserById'](arg1);
}

export function GetUsers() {
  return window['go']['main']['App']['GetUsers']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function ReceiveMessage(arg1) {
  return window['go']['main']['App']['ReceiveMessage'](arg1);
}

export function Register(arg1, arg2) {
  return window['go']['main']['App']['Register'](arg1, arg2);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function UpdateUser() {
  return window['go']['main']['App']['UpdateUser']();
}
